from glob import glob

datafiles = glob("raw_data/**/data.txt", recursive=True)

analysis_plots = "assets/plots/"
"""
Rule for fast analysis plots
with no reweighting.

"""


rule bootstrap_histograms:
    input:
        data=datafiles,
        src="src/bootstrap.py",
        tools="src/analysis_tools.py",
    output:
        polyakov=analysis_plots + "bootstrap_polyakov.pdf",
        susceptibility=analysis_plots + "bootstrap_susceptibility.pdf",
        binder=analysis_plots + "bootstrap_binder.pdf",
    shell:
        "python {input.src} "
        "--polyakov_plot {output.polyakov} "
        "--susceptibility_plot {output.susceptibility} "
        "--binder_plot {output.binder} "


rule reweighting_plots:
    input:
        data=datafiles,
        src="src/reweighting_plots.py",
        tools="src/analysis_tools.py",
    output:
        polyakov=analysis_plots + "reweighted_polyakov.pdf",
        susceptibility=analysis_plots + "reweighted_susceptibility.pdf",
        binder=analysis_plots + "reweighted_binder.pdf",
    shell:
        "python {input.src} "
        "--polyakov_plot {output.polyakov} "
        "--susceptibility_plot {output.susceptibility} "
        "--binder_plot {output.binder} "


rule quick_analysis:
    input:
        script="src/quick_analysis.py",
        file=lambda wc : f"raw_data/L{wc.L}/B{wc.B}/data.txt"
    output: "intermediary_data/analysis/L{L}/B{B}/data.json"
    shell:
        "python {input.script} --file {input.file} --output {output}"


rule boostrap_rw:
    input:
        lambda wc: glob(f"raw_data/L{wc.L}/**/data.txt", recursive=True),
    output:
        "intermediary_data/reweights/L{L}.txt",
    shell:
        "python src/simple_rw.py "
        "--files {input} > {output}"


rule plaquette:
    input:
        data=datafiles,
        src="src/plaquette.py",
    output:
        polyakov=analysis_plots + "plaquette.pdf",
        susceptibility=analysis_plots + "plaquette_susceptibility.pdf",
        binder=analysis_plots + "plaquette_binder.pdf",
    shell:
        "python {input.src} "
        "--plaquette_plot {output.polyakov} "
        "--susceptibility_plot {output.susceptibility} "
        "--binder_plot {output.binder} "


rule analysis_plots:
    input:
        data=datafiles,
        src="src/analysis_plots.py",
        tools="src/analysis_tools.py",
    output:
        polyakov=analysis_plots + "polyakov.pdf",
        susceptibility=analysis_plots + "susceptibility.pdf",
        binder=analysis_plots + "binder.pdf",
    shell:
        "python {input.src} "
        "--polyakov_plot {output.polyakov} "
        "--susceptibility_plot {output.susceptibility} "
        "--binder_plot {output.binder} "


rule clean:
    shell:
        "rm -rf assets/"
