from glob import glob

datafiles = glob("raw_data/**/data.txt", recursive=True)

analysis_plots = "assets/plots/"
"""
Rule for fast analysis plots
with no reweighting.

"""

T, L, beta = glob_wildcards("raw_data/T{T}/L{L}/beta{beta}/data.txt")

rule all_histograms:
    input:
        expand("assets/histograms/T{T}_L{L}_beta{beta}_action.pdf",
                zip, T=T, L=L, beta=beta)


rule get_histogram:
    input:
        script="src/hist.py",
        data="raw_data/T{T}/L{L}/beta{beta}/data.txt"
    output:
        action_hist="assets/histograms/T{T}_L{L}_beta{beta}_action.pdf",
        polyakov_hist="assets/histograms/T{T}_L{L}_beta{beta}_polyakov.pdf"
    shell:
        "python {input.script} "
        "--input {input.data} "
        "--output_action {output.action_hist} "
        "--output_polyakov {output.polyakov_hist} "
        "--L {wildcards.L} "
        "--T {wildcards.T} "       
        

rule bootstrap_histograms:
    input:
        data=datafiles,
        src="src/bootstrap.py",
        tools="src/analysis_tools.py",
    output:
        polyakov=analysis_plots + "bootstrap_polyakov.pdf",
        susceptibility=analysis_plots + "bootstrap_susceptibility.pdf",
        binder=analysis_plots + "bootstrap_binder.pdf",
    shell:
        "python {input.src} "
        "--polyakov_plot {output.polyakov} "
        "--susceptibility_plot {output.susceptibility} "
        "--binder_plot {output.binder} "


rule reweighting_plots:
    input:
        data=datafiles,
        src="src/reweighting_plots.py",
        tools="src/analysis_tools.py",
    output:
        polyakov=analysis_plots + "reweighted_polyakov.pdf",
        susceptibility=analysis_plots + "reweighted_susceptibility.pdf",
        binder=analysis_plots + "reweighted_binder.pdf",
    shell:
        "python {input.src} "
        "--polyakov_plot {output.polyakov} "
        "--susceptibility_plot {output.susceptibility} "
        "--binder_plot {output.binder} "


rule plaquette:
    input:
        data=datafiles,
        src="src/plaquette.py",
    output:
        polyakov=analysis_plots + "plaquette.pdf",
        susceptibility=analysis_plots + "plaquette_susceptibility.pdf",
        binder=analysis_plots + "plaquette_binder.pdf",
    shell:
        "python {input.src} "
        "--plaquette_plot {output.polyakov} "
        "--susceptibility_plot {output.susceptibility} "
        "--binder_plot {output.binder} "


rule analysis_plots:
    input:
        data=datafiles,
        src="src/analysis_plots.py",
        tools="src/analysis_tools.py",
    output:
        polyakov=analysis_plots + "polyakov.pdf",
        susceptibility=analysis_plots + "susceptibility.pdf",
        binder=analysis_plots + "binder.pdf",
    shell:
        "python {input.src} "
        "--polyakov_plot {output.polyakov} "
        "--susceptibility_plot {output.susceptibility} "
        "--binder_plot {output.binder} "


rule clean:
    shell:
        "rm -rf assets/"
